### ISSUE TITLE
How to install the filesafe-bar?

### ISSUE THREAD

**Issue by BobWs** [standardnotes/filesafe-bar#13]
Sorry for the noob question but I’m totally new to Standardnotes but how do I install the filesafe-bar? I’ve Seen it on the demo site and I couldn’t find any documentation about how to install the FileSafe-bar.

![277EB8FD-0F38-486A-9688-DD4D2EEC7195](https://user-images.githubusercontent.com/5485820/90972390-e4debd80-e518-11ea-976f-01415f65d3e5.jpeg)

**Comment by JaspalSuri** [comment]
No need to apologize! If you're an Extended user, open the desktop or web app, click on the Extensions button near the bottom left corner, scroll down all the way down, and then scroll up until you see the FileSafe extension. 

Here's what it will look like:
![image](https://user-images.githubusercontent.com/44656000/91144747-52016880-e669-11ea-89cf-afb57ec9a47b.png)

From there, make sure to activate it and give it permission to interact with your notes. :)

To upload files, you will need to use the Bold Editor to insert them into your notes (but can download and access them from any note with any editor).  

Feel free to let us know if you have any other questions!

**Comment by BobWs** [comment]
Thanks for sharing.
At the moment I'm using the selfhost docker version https://hub.docker.com/r/standardnotes/syncing-server
So I guess that the FileSafe extension also need to be selfhosted?

**Comment by JaspalSuri** [comment]
Hi, thank you for patience and for using that version! 

> So I guess that the FileSafe extension also need to be selfhosted?

Fortunately it won't have to be, according to the dev team: 
> You would only need to self-host the relay-server. Then when adding an integration inside of FileSafe UI, you would get an integration code from your own server rather than pressing “Add Integration” in our extension's UI.

**Comment by BobWs** [comment]
> Hi, thank you for patience and for using that version!
> 
> > So I guess that the FileSafe extension also need to be selfhosted?
> 
> Fortunately it won't have to be, according to the dev team:
> 
> > You would only need to self-host the relay-server. Then when adding an integration inside of FileSafe UI, you would get an integration code from your own server rather than pressing “Add Integration” in our extension's UI.

Thanks installed it and it is working!
